### ISSUE TITLE
Open sourcing Dockerfiles

### ISSUE THREAD

**Issue by Kibouo** [alrawi/badthings-tools#1]
Would it be possible to open-source the Dockerfiles used to build the dynamic analysis images (currently hosted on Dropbox)? This would ensure reproducibility, in case Dropbox decides to take the files down for some reason, and promote open science.

**Comment by alrawi** [comment]
Hi Kibouo,
Thank you for reminding me. I was planning on doing this earlier but did not get time to do it. I will work on getting the source files for Docker and the analysis script published soon.

**Comment by Kibouo** [comment]
Thank you! This project helps tremendously with the analysis of my master thesis' data.

**Comment by alrawi** [comment]
I just pushed the docker files, helper scripts, and the build root configuration files to under `dynamic_analysis/src`.
