### ISSUE TITLE
The results of the Dynamic Analysis

### ISSUE THREAD

**Issue by lt-deng** [alrawi/badthings-tools#2]
Thanks for sharing the usage of docker images in details. However, the system call trace files are all empty when I analyze the binary given by the guidance (_4c962e8714a622d114a6b083e5eb9b2699bff4f4f04efd669020fb2d6f158e1e_). The results are shown below:
![result](https://user-images.githubusercontent.com/38178426/167053704-2cdf6a04-c46d-4eef-9899-abaa44975093.jpg)
How to solve this problem? Thank you!

**Comment by alrawi** [comment]
Thank you for submitting this issue. I am not sure what happened there, but I will try to take a look when I get time. I just pushed the source files to build the environments and docker files for running the analysis. Feel free to poke around and see if you can narrow down the issue. 

Is this happening for all binaries you are running or just this particular one?

**Comment by lt-deng** [comment]
I have checked the buildroot configuration files and vm scripts, they all work well. 
And maybe there is a written mistake in `start_vm_mipsel.sh` file. The `-m 12` need to be changed into `-m 128` for a larger space.

**Comment by alrawi** [comment]
Thank you for finding that bug. I have fixed it and pushed it to the main branch. I am going to close this issue.
