### ISSUE TITLE
Scripts Missing

### ISSUE THREAD

**Issue by lt-deng** [alrawi/badthings-tools#3]
For `m68k` architecture, the vm start script and dockerfile are not found.

**Comment by alrawi** [comment]
The dynamic analyzer does not support m68k. I had issues with building the linux kernel for m68k target architecture. I have instructions for how to use buildroot to compile a kernel for the supported target environment. If you are able to compile an environment for m68k that boots with QEMU, I can incorporate it into the project.

**Comment by lt-deng** [comment]
OK. I will try to solve this problem.
Another question is that when I run `docker build . -t arm-qemu:1.0-glibc` for docker building, I have found the errors below:
```
...
...

+ wget -O qemu-4.1.1.tar.xz https://download.qemu.org/qemu-4.1.1.tar.xz --progress=dot:giga
--2022-07-06 08:43:04--  https://download.qemu.org/qemu-4.1.1.tar.xz
Resolving download.qemu.org (download.qemu.org)... 13.107.246.40, 13.107.213.40, 2620:1ec:bdf::40, ...
Connecting to download.qemu.org (download.qemu.org)|13.107.246.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62222068 (59M) [application/x-xz]
Saving to: 'qemu-4.1.1.tar.xz'

     0K ........ ........ ........ ........ 53% 11.7M 2s
 32768K ........ ........ ........ ...     100% 6.37M=7.0s

2022-07-06 08:43:12 (8.46 MB/s) - 'qemu-4.1.1.tar.xz' saved [62222068/62222068]

+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.L0M0POZppO
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys CEACC9E15534EBABB82D3FA03353C9CEF108B584
gpg: keybox '/tmp/tmp.L0M0POZppO/pubring.kbx' created
gpg: keyserver receive failed: Server indicated a failure

...
...
```
Is there any ideas with this situation? Thank you!

**Comment by lt-deng** [comment]
> OK. I will try to solve this problem. Another question is that when I run `docker build . -t arm-qemu:1.0-glibc` for docker building, I have found the errors below:
> 
> ```
> ...
> ...
> 
> + wget -O qemu-4.1.1.tar.xz https://download.qemu.org/qemu-4.1.1.tar.xz --progress=dot:giga
> --2022-07-06 08:43:04--  https://download.qemu.org/qemu-4.1.1.tar.xz
> Resolving download.qemu.org (download.qemu.org)... 13.107.246.40, 13.107.213.40, 2620:1ec:bdf::40, ...
> Connecting to download.qemu.org (download.qemu.org)|13.107.246.40|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 62222068 (59M) [application/x-xz]
> Saving to: 'qemu-4.1.1.tar.xz'
> 
>      0K ........ ........ ........ ........ 53% 11.7M 2s
>  32768K ........ ........ ........ ...     100% 6.37M=7.0s
> 
> 2022-07-06 08:43:12 (8.46 MB/s) - 'qemu-4.1.1.tar.xz' saved [62222068/62222068]
> 
> + mktemp -d
> + export GNUPGHOME=/tmp/tmp.L0M0POZppO
> + gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys CEACC9E15534EBABB82D3FA03353C9CEF108B584
> gpg: keybox '/tmp/tmp.L0M0POZppO/pubring.kbx' created
> gpg: keyserver receive failed: Server indicated a failure
> 
> ...
> ...
> ```
> 
> Is there any ideas with this situation? Thank you!

Hi, I think the problem is about the key server. The dockerfile works well when I have changed `ha.pool.sks-keyservers.net` to `keyserver.ubuntu.com`.
