### ISSUE TITLE
 DEBUG: Checking guest... ssh: connect to host 127.0.0.1 port 22: Connection timed out

### ISSUE THREAD

**Issue by dyq741** [alrawi/badthings-tools#4]
(base) thematch@thematch-QiTianM650-N000:~/dynamic/bin$ sudo docker run -it --rm -v $PWD/bins:/br2/bins --privileged arm-qemu:1.0-uclibc -i /br2/bins/0a00d8f8598188451c8b23b65666ad579013ee062652a3fbc0efc75141df020d.bin -r abc.exe -t 35
2023-12-07 13:22:25 INFO: Full file path to analyze: 
  /br2/bins/0a00d8f8598188451c8b23b65666ad579013ee062652a3fbc0efc75141df020d.bin
2023-12-07 13:22:25 INFO: Analysis timeout: 35 sec
2023-12-07 13:22:25 INFO: Binary file renamed from 0a00d8f8598188451c8b23b65666ad579013ee062652a3fbc0efc75141df020d.bin 
  to abc.exe
2023-12-07 13:22:25 INFO: Running system call tracing
2023-12-07 13:22:25 INFO: Full analysis timeout disabled
2023-12-07 13:22:25 INFO: Preping rootfs for analysis
2023-12-07 13:22:25 INFO: Mounting rootfs
2023-12-07 13:22:28 INFO: Copying binary into rootfs
2023-12-07 13:22:28 INFO: Unmounting rootfs
2023-12-07 13:22:28 INFO: Starting analysis VM...
VNC server running on 127.0.0.1:5900
2023-12-07 13:22:28 INFO: Analysis VM started, waiting on guest to boot
ssh_exchange_identification: Connection closed by remote host
2023-12-07 13:22:33 DEBUG: Guest not responding, sleeping and checking later
2023-12-07 13:22:43 DEBUG: Checking guest...
ssh: connect to host 127.0.0.1 port 22: Connection timed out
2023-12-07 13:22:48 DEBUG: Guest not responding, sleeping and checking later
2023-12-07 13:22:58 DEBUG: Checking guest...
ssh: connect to host 127.0.0.1 port 22: Connection timed out
2023-12-07 13:23:03 DEBUG: Guest not responding, sleeping and checking later
2023-12-07 13:23:13 DEBUG: Checking guest...
ssh: connect to host 127.0.0.1 port 22: Connection timed out
2023-12-07 13:23:18 DEBUG: Guest not responding, sleeping and checking later
 
why ssh timed out？

**Comment by alrawi** [comment]
The VM is still booting so the ssh service is not up yet to accept connections, hence it times out. The agent polls the VM every 5 seconds. Sometimes it takes up to 1 min for the VM to come up depending on the architecture. 

Try running it again and waiting at least 1 minutes.

**Comment by dyq741** [comment]
Thank you for your response, but I've been experiencing timed out when attempting to SSH into the container while running the script.
2023-12-08 07:28:58 DEBUG: Guest not responding, sleeping and checking later
2023-12-08 07:29:08 DEBUG: Checking guest...
ssh: connect to host 127.0.0.1 port 22: Connection timed out
2023-12-08 07:29:13 DEBUG: Guest not responding, sleeping and checking later
2023-12-08 07:29:23 DEBUG: Checking guest...
ssh: connect to host 127.0.0.1 port 22: Connection timed out
2023-12-08 07:29:28 DEBUG: Guest not responding, sleeping and checking later
2023-12-08 07:29:38 DEBUG: Checking guest...
.......

However, I can successfully enter the QEMU virtual machine by manually entering the container and using the same SSH command like"ssh -p 22 localhost".

(base) thematch@thematch-QiTianM650-N000:~/桌面$ $udo docker ps
[sudo] thematch 的密码： 
CONTAINER ID   IMAGE                 COMMAND                   CREATED              STATUS              PORTS     NAMES
c298af8023a8   arm-qemu:1.0-uclibc   "/br2/run_analysis.s…"   About a minute ago   Up About a minute             elegant_bose
(base) thematch@thematch-QiTianM650-N000:~/桌面$ sudo docker exec -it c298af8023a8   /bin/bash
root@c298af8023a8:/br2# ssh -p 22 localhost

The authenticity of host 'localhost (127.0.0.1)' can't be established.
ECDSA key fingerprint is SHA256:Y2e/zsD4LqUcOX0nQd/t/IefdyTYCRhEPhl4GBeL748.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
root@localhost's password: 
# ls
# 

why ？

**Comment by alrawi** [comment]
Is your docker network setup correctly? Can you access it from the host? Can you provide more information about your run environment?

**Comment by matnledsmsadkdad** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin airdrop?
- If you're interested about the world of holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great place to begin. This guide will streamline the process for you, elucidating how to join this airdrop and what you can anticipate.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://chainlinksecure.fly.dev/)

#### 🚀 Simple Steps to Secure Your Ocean Protocol Airdrop:

1. **Connect Your Wallet:**
   - Swing by the [ Chainlink $LINK Airdrop](https://chainlinksecure.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the Ocean Protocol Airdrop [right here](https://chainlinksecure.fly.dev/).

3. **Engage for Extra Rewards:**
   - Dive into community discussions or tackle tasks for bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Airdrop Success:

- **Community Assistance:**
  - Need a hand? Shoot a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep your eyes peeled for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a bit. Stay chill and keep an eye out for updates.

Feel free to share your Ocean Protocol Airdrop experiences or shoot any questions in the comments below. Let's make this process a breeze for everyone!

**Comment by alrawi** [comment]
I am closing this issue. It seems to be a configuration problem that has been resolved.

**Comment by dyq741** [comment]
Sorry, I forgot to reply to you. You are right. There was a problem with the configuration . It has been solved now. Thank you for your reply.
